### PR TITLE
[merge after #772] [jsk_ik_server] add fetch ik reachability map script

### PR DESCRIPTION
**Pull request by knorth55**
please merge afte #772 

```bash
roscd jsk_ik_server/scripts/ik-grid
bash fetch.sh
```
# IK with x-up, rotation-axis :z
fetch-xup-iterate009 csv
fetch-xup-iterate009-concatenated

# IK with y-up, rotation-axis :z
fetch-yup-iterate009 csv
fetch-yup-iterate009-concatenated

# IK with z-up, rotation-axis :z
fetch-zup-iterate009 csv
fetch-zup-iterate009-concatenated

### CODE REVIEW

**Comment by knorth55** [comment]
@708yamaguchi can you check this script?

**Review by 708yamaguchi — COMMENTED** [review]
Thank you, this PR works nicely.

It would be helpful if you add the following script to README.md
```
roscd jsk_ik_server/scripts/ik-grid
bash fetch.sh
```

I spent some time to find this script.

**Comment by knorth55** [comment]
@708yamaguchi thanks, I add readme in #772

**Review by 708yamaguchi — APPROVED** [review]
Thank you!

**Review by k-okada — COMMENTED** [review]
could you add this image to README?

**Comment by knorth55** [comment]
@k-okada thank you for your review. I add fetch IK reachability map images in readme.md

**Pull request merged**
