### PR TITLE
[jsk_footstep_planner] Use quaternion-from-two-vectors to compute rotate in project-coords-on-to-plane

### PR DESCRIPTION
**Pull request by garaemon**
@k-kimura Please check this

### CODE REVIEW

**Comment by garaemon** [comment]
@k-kimura  You may also need to update jskeus in order to use this

**Comment by k-kimura** [comment]
@garaemon Thank you very much.
I tried to check the function *"project-coords-on-to-plane"* on *footstep_planner_util.l*, but I got the error following:
when
```lisp
(load "package://jsk_footstep_planner/euslisp/footstep_planner_util.l")
(project-coords-on-to-plane (send (send *robot* :rleg :end-coords :copy-worldcoords) :translate (float-vector 280 0 300) :world) *terrain-faces* (float-vector 0 0 1))
```
the following error occured.
```lisp
/home/k-kimura/ros/hydro/src/jsk-ros-pkg/jsk_roseus/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: undefined function quaternion-from-two-vectors in (quaternion2matrix (quaternion-from-two-vectors (float-vector 0 0 1) (send p :normal)))
```

Here,to define function *quaternion-from-two-vectors*, I tried to update *jskeus/irteus/irtgeo.l* as https://github.com/euslisp/jskeus/pull/174.
```
roscd euslisp
cd jskeus/irteus
git pull
make
```
However the same error reproduced.
Could you tell me the solution about this?
And I'm sorry to report basic error.

**Comment by garaemon** [comment]
Have you updated jskeus and compile it?

2015年3月24日火曜日、Kohei Kimura<notifications@github.com>さんは書きました:

> @garaemon <https://github.com/garaemon> Thank you very much.
> I tried to check the function *"project-coords-on-to-plane"* on
> *footstep_planner_util.l*, but I got the error following:
> when
>
> (load "package://jsk_footstep_planner/euslisp/footstep_planner_util.l")
> (project-coords-on-to-plane (send (send *robot* :rleg :end-coords :copy-worldcoords) :translate (float-vector 280 0 300) :world) *terrain-faces* (float-vector 0 0 1))
>
> the following error occured.
>
> /home/k-kimura/ros/hydro/src/jsk-ros-pkg/jsk_roseus/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: undefined function quaternion-from-two-vectors in (quaternion2matrix (quaternion-from-two-vectors (float-vector 0 0 1) (send p :normal)))
>
> Here,to define function *quaternion-from-two-vectors*, I tried to update
> *jskeus/irteus/irtgeo.l* as euslisp/jskeus#174
> <https://github.com/euslisp/jskeus/pull/174>.
>
> roscd euslisp
> cd jskeus/irteus
> git pull
> make
>
> However the same error reproduced.
> Could you tell me the solution about this?
> And I'm sorry to report basic error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_control/pull/251#issuecomment-85073891>
> .
>


-- 
✉︎ from iPhone

**Comment by k-kimura** [comment]
> Have you updated jskeus and compile it?

I updated and compiled only jskeus/irteus by git pull & make.
Is it ok for my old catkin_make environment to update jskeus and compile it?

**Comment by garaemon** [comment]
catkin_make is ok

**Comment by garaemon** [comment]
sorry my fault, it should solve the issue
https://github.com/jsk-ros-pkg/jsk_control/pull/253

**Comment by k-kimura** [comment]
I have updated *jskeus* and *jsk_footstep_planner*, and compiled *jskeus*.
As a result of this, the error problem seems to be solved.
Thank you very much.
I attach the screenshots about the project-coords-view to terrain-faces by *(project-coords-on-to-plane)*
```lisp
(send (send (send *robot* :rleg :end-coords :copy-worldcoords) :translate (float-vector 280 0 300) :world) :draw-on :flush t :size 100 :color #f(0 1 0))
(send (car (project-coords-on-to-plane (send (send *robot* :rleg :end-coords :copy-worldcoords) :translate (float-vector 280 0 300) :world) *terrain-faces* (float-vector 0 0 1))) :draw-on :flush t :size 100 :color #f(1 0 0))
```
project-coords-on-to-plane
project-coords-on-to-plane_side

**Comment by garaemon** [comment]
It should be solved now by https://github.com/jsk-ros-pkg/jsk_control/pull/254

**Pull request merged**
