### PR TITLE
[eus_qpoases] use ExternalProject instead of mk

### PR DESCRIPTION
**Pull request by furushchev**
Building another CMake Project using `mk` package does not propagate any environment/cmake configure variables, which may cause errors.

### CODE REVIEW

**Comment by snozawa** [comment]
LGTM.

> which may cause errors.

Could you paste the error messages?

**Comment by garaemon** [comment]
`  <build_depend>subversion</build_depend>` is needed.

**Comment by snozawa** [comment]
I confirmed `<build_depend>subversion</build_depend>` is added.

**Comment by garaemon** [comment]
> <build_depend>subversion</build_depend> is needed.

already added

**Comment by furushchev** [comment]
Error may varies.because environment variables are different along with environments.
The problem is if you use sub-`cmake` or sub-`make` in `execute_process`, most of environment variables are NOT passed from parent-`cmake`.
In my environment, it caused link errors:

```bash
Linking CXX shared library libs/libqpOASES.so                                                         
make[3]: Leaving directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'               
[ 61%] Built target qpOASES                                                                           
make[3]: Entering directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'              
Scanning dependencies of target example1                                                              
make[3]: Leaving directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'               
make[3]: Entering directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'              
[ 65%] Building CXX object CMakeFiles/example1.dir/examples/example1.cpp.o                            
Linking CXX executable bin/example1                                                                   
CMakeFiles/example1.dir/examples/example1.cpp.o:(.eh_frame+0x13): undefined reference to `__gxx_person
ality_v0' 
libs/libqpOASES.so.3.0: undefined reference to `operator delete(void*)'                               
libs/libqpOASES.so.3.0: undefined reference to `operator new[](unsigned long)'                        
libs/libqpOASES.so.3.0: undefined reference to `__cxa_pure_virtual'                                   
libs/libqpOASES.so.3.0: undefined reference to `operator delete[](void*)'                             
libs/libqpOASES.so.3.0: undefined reference to `vtable for __cxxabiv1::__si_class_type_info'          
libs/libqpOASES.so.3.0: undefined reference to `operator new(unsigned long)'                          
libs/libqpOASES.so.3.0: undefined reference to `sqrt'                                                 
libs/libqpOASES.so.3.0: undefined reference to `vtable for __cxxabiv1::__class_type_info'             
libs/libqpOASES.so.3.0: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info'         
collect2: ld returned 1 exit status                                                                   
make[3]: *** [bin/example1] Error 1                                                                   
make[3]: Leaving directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'               
make[2]: *** [CMakeFiles/example1.dir/all] Error 2                                                    
make[2]: Leaving directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'               
make[1]: *** [all] Error 2                                                                            
make[1]: Leaving directory `/home/furushchev/ros/hydro/build/eus_qpoases/build/qpOASES'               
make: *** [installed] Error 2                                                                         
CMake Error at CMakeLists.txt:13 (message):                                                           
  Build of qpOASES failed                                                                             
                                                                                                      
-- Configuring incomplete, errors occurred!                                                           
[eus_qpoases] <== '/home/furushchev/ros/hydro/build/eus_qpoases/build_env.sh /usr/bin/cmake /home/furushchev/ros/hydro/src/jsk-ros-pkg/jsk_control/eus_qpoases -DCATKIN_DEVEL_PREFIX=/home/furushchev/ros/hydro/devel -DCMAKE_INSTALL_PREFIX=/home/furushchev/ros/hydro/install -DCMAKE_BUILD_TYPE=Release' failed with return code '1' 
Failed   <== eus_qpoases [ 27.6 seconds ] 
```

**Comment by furushchev** [comment]
BTW, I suspect that this type of problem essentially is related to the curious behavior of catkin/cmake I found, which is, I don't know why, environment variables passed to `cmake` are different on the first time executing `catkin build` and on the second time.

**Comment by k-okada** [comment]
> libs/libqpOASES.so.3.0: undefined reference to `operator delete(void*)'                               

this usually because of gcc/g++ version difference.

**Pull request merged**
