### PR TITLE
add cmd_vel_smoother package

### PR DESCRIPTION
**Pull request by furushchev**
This is revised version of https://github.com/jsk-ros-pkg/jsk_control/pull/480
Please see [README.md](https://github.com/furushchev/jsk_control/blob/3c2fb953c44228e27d1f38319e4e90e12395f042/cmd_vel_smoother/README.md) for detail

### CODE REVIEW

**Comment by k-okada** [comment]
@longjie do you know if turtlebot already have slimier nodes?

**Comment by furushchev** [comment]
@k-okada Maybe this is to me? :)
I found this package: https://github.com/yujinrobot/yujin_ocs/tree/devel/yocs_velocity_smoother
Need to compare?

**Comment by k-okada** [comment]
no, i'm asking to @longjie  (you'd bettert to put icon images so other can recognize), but if you find that , that's ok. and if there is an existing node, we'd check if are not re-inventing wheels.

**Comment by furushchev** [comment]
@k-okada Please review and merge if there is no problem.

**Comment by k-okada** [comment]
please update README
- please add link to issue, for example, This problem is reported and discussed in https://github.com/ros-planning/navigation/issues/405
- Did you find this idea by your self? or motivated by https://github.com/yujinrobot/yujin_ocs/tree/devel/yocs_velocity_smoother, anyway add turtlebot?
 has similar idea to solve this problem http://...

**Comment by furushchev** [comment]
@k-okada Thank you for review! Updated readme. The basic idea is very simple and I did not see any other packages since I thought that it is the unique problem for PR2 at that time.

**Pull request merged**
