### PR TITLE
Project odom_init to detected floor

### PR DESCRIPTION
**Pull request by orikuma**
please merge after https://github.com/jsk-ros-pkg/jsk_control/pull/577 and https://github.com/jsk-ros-pkg/jsk_recognition/pull/1576 .
Default behavior is same as before.

### CODE REVIEW

**Comment by orikuma** [comment]
This error should occur because https://github.com/jsk-ros-pkg/jsk_recognition/pull/1576 is missing

**Comment by k-okada** [comment]
ok, i have merged the  jsk-ros-pkg/jsk_recognition#1576 and restarted travsi

--
◉ Kei Okada

**Comment by orikuma** [comment]
ros-hydro-jsk-recognition-utils seems not to be updated since 20150911 and it causes compile errors in hydro test (ros-indigo-jsk-recognition-utils is updated in 20160514 and test passed in indigo).
How can I solve this version problem in hydro?

**Comment by k-okada** [comment]
add latest released jsk_recognition_utils to .travis.rosinstall.hydro see
use config section of https://github.com/jsk-ros-pkg/jsk_travis

--
◉ Kei Okada

**Comment by orikuma** [comment]
Test passed. Please merge.
Thanks to @wkentaro.

**Comment by orikuma** [comment]
Please merge, this PR is needed to compensate odom offset in footstep plannning

**Comment by orikuma** [comment]
Please merge

**Pull request merged**
