### PR TITLE
Add follow_path heuristic to footstep_planner

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
DO NOT MERGE YET

### CODE REVIEW

**Comment by YoheiKakiuchi** [comment]
hydro:
error occured by boost from code in jsk_recognition_utils
~~~
[jsk_footstep_planner] In file included from /usr/include/boost/signals2.hpp:20:0,
[jsk_footstep_planner]                  from /usr/include/pcl-1.7/pcl/io/boost.h:73,
[jsk_footstep_planner]                  from /usr/include/pcl-1.7/pcl/io/file_io.h:43,
[jsk_footstep_planner]                  from /usr/include/pcl-1.7/pcl/io/pcd_io.h:44,
[jsk_footstep_planner]                  from /opt/ros/hydro/include/pcl_conversions/pcl_conversions.h:69,
[jsk_footstep_planner]                  from /home/travis/ros/ws_jsk_control/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl_conversion_util.h:40,
[jsk_footstep_planner]                  from /home/travis/ros/ws_jsk_control/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/geo/polygon.h:50,
[jsk_footstep_planner]                  from /home/travis/ros/ws_jsk_control/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/geo_util.h:75,
[jsk_footstep_planner]                  from /home/travis/ros/ws_jsk_control/src/jsk_control/jsk_footstep_planner/include/jsk_footstep_planner/footstep_graph.h:48,
[jsk_footstep_planner]                  from /home/travis/ros/ws_jsk_control/src/jsk_control/jsk_footstep_planner/src/footstep_graph.cpp:36:
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:78:9: error: wrong number of template arguments (6, should be 5)
[jsk_footstep_planner] /usr/include/boost/parameter/parameters.hpp:714:8: error: provided for template<class PS0, class PS1, class PS2, class PS3, class PS4> struct boost::parameter::parameters
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:83:9: error: parameter_spec is not a class or namespace
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:83:29: error: expected unqualified-id before < token
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:99:11: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:105:9: error: template argument 1 is invalid
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:108:31: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:108:67: error: template argument 1 is invalid
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:111:31: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:111:94: error: template argument 1 is invalid
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:115:31: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:115:97: error: template argument 1 is invalid
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:121:13: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:124:11: error: template argument 1 is invalid
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:128:31: error: args was not declared in this scope
[jsk_footstep_planner] /usr/include/boost/signals2/signal_type.hpp:128:69: error: template argument 1 is invalid
[jsk_footstep_planner] make[2]: *** [CMakeFiles/jsk_footstep_planner.dir/src/footstep_graph.cpp.o] Error 1
[jsk_footstep_planner] make[2]: *** Waiting for unfinished jobs....
[jsk_footstep_planner] Scanning dependencies of target jsk_footstep_planner_generate_messages
[jsk_footstep_planner] [ 94%] Built target jsk_footstep_planner_generate_messages
[jsk_footstep_planner] make[1]: *** [CMakeFiles/jsk_footstep_planner.dir/all] Error 2
[jsk_footstep_planner] make: *** [all] Error 2
[jsk_footstep_planner] <== '/home/travis/ros/ws_jsk_control/build/jsk_footstep_planner/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
Failed <== jsk_footstep_planner    [ 57.3 seconds ]
]2;[build] There were '1' errors:
~~~

kinetic:
version 1.1.3 of jsk_recognition_utils does not exists yet
http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-kinetic-jsk-recognition-utils/

**Comment by k-okada** [comment]
released on kinetic -> https://github.com/ros/rosdistro/pull/15488
on hydro, we are testing jsk_recognition for hydro on travis (https://travis-ci.org/jsk-ros-pkg/jsk_recognition), so why this error happens?

**Comment by YoheiKakiuchi** [comment]
DO NOT MERGE YET
I will clean up commits

**Comment by YoheiKakiuchi** [comment]
> on hydro, we are testing jsk_recognition for hydro on travis (https://travis-ci.org/jsk-ros-pkg/jsk_recognition), so why this error happens?

It is old boost and pcl problem. We can solve this problem by including pcl headers before including another boost headers.
http://boost.2283326.n4.nabble.com/Accumulators-Signals2-Compilation-error-with-GCC-when-both-are-used-td3585468.html

**Pull request merged**
