### PR TITLE
[jsk_footstep_planner] separate standalone utility functions into footstp_planner_util.l

### PR DESCRIPTION
**Pull request by garaemon**
@snozawa 
for example, 
```
(send-all (project-coords-on-to-plane
           (make-coords) (send (make-cube 100 100 100) :faces)
           (float-vector 0 0 1))
          :draw-on :flush t)
```

screenshot_from_2015-03-18 01 51 07

### CODE REVIEW

**Comment by snozawa** [comment]
Thanks!!

I tried your function.
snap
Blue is input coords and red is result coords.

How do you determine position of result coords?
Position of red differs from position of red.

**Comment by garaemon** [comment]
The position is projected onto the plane along with the normal vector of the plane.

**Comment by snozawa** [comment]
Thanks.

Do you have any function to get one sole plane or polygon on Euslisp?

**Comment by garaemon** [comment]
> Do you have any function to get one sole plane or polygon on Euslisp?

of what?

**Comment by snozawa** [comment]
I saw hrp2 footsteps ware displayed as green rectangles and red rectangles on RVIZ.
I think you have functions to make footstep polygons.

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_planner/euslisp/footstep-planner-node.l#L267

I'm sorry that I provide the parameter directly via ros-param.

**Pull request merged**
